services:
  postgres:
    image: 'postgres:latest'
    environment:
      - 'POSTGRES_DB=sandbox_db'
      - 'POSTGRES_PASSWORD=postgres'
      - 'POSTGRES_USER=postgres'
    ports:
      - '6432:5432'
    restart: always
