
## load external properties
#load:
#  properties: ${user.home}/config/my-application.properties
ebean:
  dbSchema: ${db.username:sandbox_db}
  migration:
    run: true
    autoCreate: true

datasource:
  db:
    username: ${db.username:postgres}
    password: ${db.password:postgres}
    url: ${db.url:jdbc:postgresql://localhost:6432/sandbox_db}
